config/routes.rb
Rails.application.routes.draw do
  root to: "home#template_index"
  
  resources :users
  resources :schools
  
  # Sessions
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :users
  
  scope :draft, -> { where(status: 0) }
  scope :active, -> { where(status: 1) }
  scope :fund_raising, -> { where(status: 2) }
  scope :built, -> { where(status: 3) }

  enum status: {
    draft: 0,
    active: 1,
    fund_raising: 2,
    built: 3
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :school, optional: true
  before_save :set_default_role

  ROLES = %w(admin member student).freeze

  private

  def set_default_role
    role = 'member' if role.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    if params[:status].present?
      @schools = School.send(params[:status]).order('created_at DESC')
    else
      @schools = School.all.order('updated_at DESC')
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :description, :contact, :address, :status, :admin_note)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    @user = User.find_by('lower(email) = ?', params[:email].downcase)
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'Logged in Sucessfully'
      redirect_to root_path
    else
      respond_to do |format|
        format.html do
          flash[:error] = 'Incorrect email address or password'
          render 'new'
        end

        format.json do
          render status: :forbidden, json: { error: 'Incorrect email address or password' }
        end
      end
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil

    flash[:notice] = 'Logged Out!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :login_required, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:show, :edit, :update, :destroy]

  attr_accessor :password, :password_confirmation

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :address, :role, :admin_note, :school_id)
    end

    def login_required
      redirect_to login_path if current_user.nil?
    end

    def authorize_admin
      unless admin_user? || current_user = @user
        flash[:danger] = 'Not Authorized'
        redirect_to login_path 
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id].nil?
      @current_user = nil
      return nil
    end

    return @current_user unless @current_user.nil?
    @current_user = User.find(session[:user_id])
  end

  def admin_user?
    current_user.present? && current_user.role == 'admin'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper

  def readable_school_statuses
    arr = []
    School.statuses.keys.each do |k|
      case k
      when 'draft'
        arr << ['Nháp', k]
      when 'active'
        arr << ['Tạo xong' , k]
      when 'fund_raising'
        arr << ['Đang Gây Quỹ', k]
      when 'built'
        arr << ['Đã Khánh Thành', k]
      end
    end
    arr
  end

  def school_table_class(school)
    return 'table-secondary' if school.draft?
    return 'table-active' if school.active?
    return 'table-danger' if school.fund_raising?
    return 'table-success' if school.built?
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def role_options
    arr = []
    User::ROLES.each do |role|
      case role
      when 'student'
        arr << ['Học Sinh', role]
      when 'member'
        arr << ['Thành Viên', role]
      when 'admin'
        arr << ['Admin', role]
      end
    end
    arr
  end
end

app/views/home/generic.html.erb
<!DOCTYPE HTML>
<!--
	Transitive by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Generic - Transitive by TEMPLATED</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<%# <link rel="stylesheet" href="assets/css/main.css" /> %>
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="index.html">Transitive <span>by TEMPLATED</span></a></div>
				<a href="#menu" class="toggle"><span>Menu</span></a>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="generic.html">Generic</a></li>
					<li><a href="elements.html">Elements</a></li>
				</ul>
			</nav>

		<!-- One -->
			<section id="one" class="wrapper style2">
				<div class="inner">
					<div class="box">
						<div class="image fit">
							<img src="<%= asset_path('pic01.jpg') %>" alt="" />
						</div>
						<div class="content">
							<header class="align-center">
								<h2>Lorem ipsum dolor</h2>
								<p>maecenas feugiat ex purus, quis volutpat lacus placerat</p>
							</header>
							<hr />
							<p> Cras aliquet urna ut sapien tincidunt, quis malesuada elit facilisis. Vestibulum sit amet tortor velit. Nam elementum nibh a libero pharetra elementum. Maecenas feugiat ex purus, quis volutpat lacus placerat malesuada. Praesent in sem ex. Morbi mattis sapien pretium tellus venenatis, at egestas urna ornare.</p>
							<p>Vivamus fermentum nibh vel pharetra blandit. Cras a purus urna. Sed et libero ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse id hendrerit felis. Nulla viverra tempor dui at congue. Pellentesque quis nulla ornare, congue nisi id, finibus nulla. Aliquam sit amet hendrerit purus. Donec libero massa, posuere fermentum eros sit amet, maximus fringilla augue. Maecenas at rhoncus lorem. Vivamus ultricies consequat est, efficitur convallis libero. Vivamus rutrum semper mauris, vitae consequat eros tempor ac. Pellentesque et ornare sapien</p>
						</div>
					</div>
				</div>
			</section>

		<!-- Four -->
			<section id="four" class="wrapper style3">
				<div class="inner">

					<header class="align-center">
						<h2>Morbi interdum mollis sapien</h2>
						<p>Cras aliquet urna ut sapien tincidunt, quis malesuada elit facilisis. Vestibulum sit amet tortor velit. Nam elementum nibh a libero pharetra elementum. Maecenas feugiat ex purus, quis volutpat lacus placerat malesuada. Praesent in sem ex. Morbi mattis sapien pretium tellus venenatis, at egestas urna ornare.</p>
					</header>

				</div>
			</section>

		<!-- Footer -->
			<footer id="footer" class="wrapper">
				<div class="inner">
					<section>
						<div class="box">
							<div class="content">
								<h2 class="align-center">Get in Touch</h2>
								<hr />
								<form action="#" method="post">
									<div class="field half first">
										<label for="name">Name</label>
										<input name="name" id="name" type="text" placeholder="Name">
									</div>
									<div class="field half">
										<label for="email">Email</label>
										<input name="email" id="email" type="email" placeholder="Email">
									</div>
									<div class="field">
										<label for="dept">Department</label>
										<div class="select-wrapper">
											<select name="dept" id="dept">
												<option value="">- Category -</option>
												<option value="1">Manufacturing</option>
												<option value="1">Shipping</option>
												<option value="1">Administration</option>
												<option value="1">Human Resources</option>
											</select>
										</div>
									</div>
									<div class="field">
										<label for="message">Message</label>
										<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
									</div>
									<ul class="actions align-center">
										<li><input value="Send Message" class="button special" type="submit"></li>
									</ul>
								</form>
							</div>
						</div>
					</section>
					<div class="copyright">
						&copy; Untitled Design: <a href="https://templated.co/">TEMPLATED</a>. Images <a href="https://unsplash.com/">Unsplash</a> Video <a href="http://coverr.co/">Coverr</a>.
					</div>
				</div>
			</footer>

		<!-- Scripts -->
			<%# <script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script> %>

	</body>
</html>

app/views/home/index.html.erb
<div class="jumbotron-background p-5" style="background-image: url(<%= asset_path('jumbotron_bg.jpg') %>)">
  <h1 class="display-4">Thiện Nguyện Hoa Phượng</h1>
  <p class="lead">Trái tim nhân ái sẽ kết nối trái tim nhân ái!</p>
  <hr class="spacer">
  <hr class="spacer">
  <hr class="spacer">
  <hr class="spacer">
  <hr class="spacer">
  <hr class="spacer">
  <hr class="spacer">
  
  <!-- <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Chung tay đóng góp</a> -->
</div>

<hr class="spacer">

<div class="container">
  <h3>Thiện Nguyện Hoa Phượng thực hiện dự án #Nuôi_Em cho các cháu có hoàn cảnh khó khăn tại các tỉnh miền núi phía Bắc.</h3>

  <p>Mỗi cháu sẽ được nhận bữa ăn trưa hoặc sáng và chiều là 8,5k/bữa (150k/tháng) gồm cơm , rau thịt hoặc cá hoặc sữa, để trưa các cháu không phải đi bộ xa về nhà hoặc cầm túi cơm trắng đi ăn .</p>

  <p>Các mạnh thường quân sẽ nhận 1 cháu có mã số gửi . Sau đó vui lòng chuyển 3 tháng 1 lần hoặc 6 tháng 1 lần , hoặc cả năm học là 9 tháng theo số tk sau . Bên Hoa Phượng sẽ gửi trực tiếp cho các thầy cô chăm lo cho các cháu hàng tháng .</p>

  <p>Một tháng Nhóm sẽ báo cáo tình hình , gửi ảnh cho các bố mẹ nuôi nắm Thông tin.</p>

  <p>Cảm ơn quý mạnh thường quân đã quan tâm tới dự án .</p>

  <p>Ủng hộ tiền mặt ( xin ghi rõ họ tên và mã con nuôi ) gửi Tk :</p>

  <p>Số TK: 160314849073405 Nguyen Thi Dung -Eximbank Hai Phong.</p>
  <p>Hoặc : số TK : 0491001583298 Phạm Minh Chiến- vietcombank chi nhánh Thăng Long Hn</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoa Phuong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar navbar-expand-lg scrolling-navbar p-3'>
      <a href="/"  class='navbar-brand navbar-adjust mt-0 brand'>
        <img src="<%= asset_path('hoa_phuong_logo.jpg') %>" width='80' height='auto' class='d-inline-block img-fluid top-logo'>
      </a>
      <div class='collapse topnav navbar-collapse cl-effect-14 c'>
        <ul class='navbar-nav ml-auto'>
          <li class="nav-item dropdown pr-3">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="<%= schools_path %>" role="button" aria-haspopup="true" aria-expanded="false">XÂY TRƯỜNG</a>
            <div class="dropdown-menu">
              <%= link_to 'Điểm Trường Đang Gây Quỹ', schools_path(status: :fund_raising), class: "dropdown-item" %>
              <%= link_to 'Điểm Trường Đã Xây', schools_path(status: :built), class: "dropdown-item" %>
              <% if admin_user? %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Tất cả Điểm Trường', schools_path, class: "dropdown-item" %>
                <%= link_to 'Tạo Trường Mới', new_school_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown pr-3">
            <a class="nav-link dropdown-toggle" id="nav-lunch-projects" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">NUÔI EM</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Điểm Trường Đã Nhận</a>
              <a class="dropdown-item" href="#">Điểm Trường Cần Trợ Giúp</a>
              <a class="dropdown-item" href="#">Cập Nhật Hàng Quý</a>
            </div>
          </li>
          <li class="nav-item pr-3">
            <a class="nav-link" href="#">HOẠT ĐỘNG KHÁC</a>
          </li>
          <li class="nav-item dropdown pr-3">
            <a class="nav-link dropdown-toggle" id='nav-users' data-toggle="dropdown" href="<%= users_path %>" role="button" aria-haspopup="true" aria-expanded="false">THÀNH VIÊN</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="<%= users_path %>">TẤT CẢ</a>
              <% if current_user.present? %>
                <%= link_to 'ĐĂNG XUẤT', logout_path, method: :delete, class: 'dropdown-item' %>
              <% else %>
                <%= link_to 'ĐĂNG NHẬP', login_path, class: 'dropdown-item' %>
                <%= link_to 'ĐĂNG KÍ THÀNH VIÊN', new_user_path, class: 'dropdown-item' %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <a class="btn btn-warning px-4" href="#">ỦNG HỘ</a>
          </li>
        </ul>
      </div>
    </nav>
    <% if notice %>
      <p class="alert-success"><%= notice %></p>
    <% elsif alert || flash[:error] %>
      <p class="alert-danger"><%= alert %> <%= flash[:error] %></p>
    <% end %>

    <%= yield %>
  </body>

  <footer class="clearfix bg-white py-3 py-xl-5 mt-3 mt-xl-5 border-top site-footer ">

    <div class="container mb-5">
      <div class="row">
        <nav class="nav nav-social justify-content-center mx-auto align-items-center align-self-lg-start justify-content-lg-start ml-lg-0">
          <span class="small nav-link">Follow Us</span>
          <a href="https://www.facebook.com/hoa.blue.3" target="_blank" class="nav-link" rel="noopener">
            sometext
            <i class="icon-facebook"></i><span class="sr-only">Thiện Nguyện Hoa Phượng Facebook</span>
          </a>
          <a href="https://twitter.com/" target="_blank" class="nav-link" rel="noopener">
            twitter
            <i class="icon-twitter"></i><span class="sr-only">@TNHoaPhuong on Twitter</span>
          </a>
          <a href="https://www.instagram.com/" target="_blank" class="nav-link" rel="noopener">
            instagram
            <i class="icon-instagram"></i><span class="sr-only">@tnhoaphuong on Instagram</span>
          </a>
        </nav>

        <div class="align-self-center mx-auto align-self-lg-end mr-lg-0">
          <p class="small text-center text-lg-right">
            Copyright &#169; 2019 Thiện Nguyện Hoa Phượng.
            <img src="<%= asset_path('hoa_phuong_logo.jpg') %>" width='80' height='auto' class='d-inline-block img-fluid top-logo'>
          </p>
        </div>
      </div>
    </div>

  </footer>
</html>

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <fieldset class="form-group">
    <% if school.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

        <ul>
          <% school.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <div class="offset-2 col-3">
        <label for="name">Tên trường</label>
      </div>
      <div class="col-5">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="offset-2 col-3">
        <label for="description">Mô Tả</label>
      </div>
      <div class="col-5">
        <%= form.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="offset-2 col-3">
        <label for="contact">Liên Lạc</label>
      </div>
      <div class="col-5">
        <%= form.text_area :contact, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="offset-2 col-3">
        <label for="address">Địa chỉ</label>
      </div>
      <div class="col-5">
        <%= form.text_area :address, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="offset-2 col-3">
        <label for="admin_note">Ghi chú</label>
      </div>
      <div class="col-5">
        <%= form.text_area :admin_note, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
        <div class="offset-2 col-3">
          <label for="role">Trạng thái</label>
        </div>
        <div class="col-5">
          <%= form.select(:status, readable_school_statuses, {}, { :class => "custom-select" }) %>
        </div>
      </div>
  </fieldset>

  <div class="actions form-group-btns row">
    <div class="offset-2 col-4">
      <%= form.submit 'Lưu', class: 'btn-primary btn-block p-2 rounded-sm' %>
    </div>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <h1>Tất Cả Điểm Trường</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Tên</th>
        <th scope="col">Mô tả</th>
        <th scope="col">Liên Hệ</th>
        <th scope="col">Địa Chỉ</th>
        <th scope="col">Ghi Chú</th>
        <th scope="col">---</th>
      </tr>
    </thead>

    <tbody>
      <% @schools.each do |school| %>
        <tr class="<%= school_table_class(school) %>">
          <td><%= school.name %></td>
          <td><%= school.description %></td>
          <td><%= school.contact %></td>
          <td><%= school.address %></td>
          <td><%= school.admin_note %></td>
          <td><%= link_to 'Xem', school %></td>
          <td><%= link_to 'Sửa', edit_school_path(school) %></td>
          <td><%= link_to 'Xoá', school, method: :delete, data: { confirm: 'Bạn Chắc Không?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Tạo Trường Mới', new_school_path %>
</div>

app/views/schools/new.html.erb
<div class='container'>
  <h1>Tạo Trường Mới</h1>

  <hr class='spacer'>

  <%= render 'form', school: @school %>
</div>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @school.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @school.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>Admin note:</strong>
  <%= @school.admin_note %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Chỉnh Sửa</h1>

  <hr class="spacer">

  <%= render 'form', user: @user %>

  <%= link_to 'Xem Chi Tiết', @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Tất Cả Thành Viên</h1>

  <hr class="spacer">
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Tên</th>
        <th scope="col">Email</th>
        <th scope="col">Điện Thoại</th>
        <th scope="col">Địa Chỉ</th>
        <th scope="col">Vai Trò</th>
        <th scope="col">Ghi Chú</th>
        <th scope="col">---</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr scope="row">
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= user.address %></td>
          <td><%= user.role %></td>
          <td><%= user.admin_note %></td>
          <td><%= link_to 'Xem', user %> | <%= link_to 'Sửa', edit_user_path(user) %> | <%= link_to 'Xoá', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Tạo Thành Viên Mới', new_user_path, class: 'btn btn-primary py-2 px-3' %>
</div>

app/views/users/new.html.erb
<h1>Đăng Kí Thành Viên</h1>

<hr class="spacer">

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Chi Tiết Về Thành Viên</h1>

  <hr class="spacer">

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Tên:
    </div>
    <div class="col-6">
      <%= @user.name %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="offset-2 col-2">
      Email:
    </div>
    <div class="col-6">
      <%= @user.email %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Điện Thoại:
    </div>
    <div class="col-6">
      <%= @user.phone %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Địa Chỉ:
    </div>
    <div class="col-6">
      <%= @user.address %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Điểm Trường:
    </div>
    <div class="col-6">
      <%= @user&.school&.name %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Vai Trò:
    </div>
    <div class="col-6">
      <%= @user.role %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="offset-2 col-2">
      Ghi Chú:
    </div>
    <div class="col-6">
      <%= @user.admin_note %>
    </div>
  </div>

  <hr class="spacer">

  <div class="row mb-2">
    <div class= offset-2>
      <%= link_to 'Sửa', edit_user_path(@user) %>
    </div>
  </div>
</div>